"""Chall

Revision ID: 0f5ad5190314
Revises: 13cb4b837d7d
Create Date: 2024-06-22 19:48:18.468173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5ad5190314'
down_revision: Union[str, None] = '13cb4b837d7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key('challenge_pkey', 'challenge', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
