"""Challen

Revision ID: 181b6a91940c
Revises: 528f52a4d32c
Create Date: 2024-06-22 19:44:00.416995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181b6a91940c'
down_revision: Union[str, None] = '528f52a4d32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('challenge_name_key', 'challenge', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('challenge_name_key', 'challenge', ['name'])
    # ### end Alembic commands ###
