"""m2m test

Revision ID: 2b956706abb4
Revises: f56526d4928b
Create Date: 2024-06-20 13:06:08.458005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b956706abb4'
down_revision: Union[str, None] = 'f56526d4928b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])

    op.create_table('userskins',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('skin_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['skin_name'], ['skin.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username', 'skin_name')
    )
    op.drop_column('user', 'skins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skins', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('userskins')
    # ### end Alembic commands ###
