"""images

Revision ID: 3c4c1501cdc9
Revises: eb71a283acd6
Create Date: 2024-06-16 23:58:02.420200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4c1501cdc9'
down_revision: Union[str, None] = 'eb71a283acd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin', sa.Column('image', sa.String(), server_default='<sqlalchemy.orm.properties.MappedColumn object at 0x0000024349B075B0>.jpg', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skin', 'image')
    # ### end Alembic commands ###
