"""qwe

Revision ID: 4e6bea8b0309
Revises: a50d3e3e8236
Create Date: 2024-06-22 22:49:39.624415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6bea8b0309'
down_revision: Union[str, None] = 'a50d3e3e8236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'challenge', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenge', type_='foreignkey')
    op.drop_column('challenge', 'user_id')
    # ### end Alembic commands ###
