"""Challeng

Revision ID: 528f52a4d32c
Revises: 2d835952e20d
Create Date: 2024-06-22 19:39:26.801674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528f52a4d32c'
down_revision: Union[str, None] = '2d835952e20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.drop_constraint('challenge_pkey', 'challenge', type_='primary')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
