"""del

Revision ID: 5518209c7ff4
Revises: 9faed4dfdf55
Create Date: 2024-06-22 23:09:49.976382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5518209c7ff4'
down_revision: Union[str, None] = '9faed4dfdf55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='challenge_pkey')
    )
    # ### end Alembic commands ###
