"""Challenge add

Revision ID: 922ca4c0bf06
Revises: 2b956706abb4
Create Date: 2024-06-22 19:36:26.443343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922ca4c0bf06'
down_revision: Union[str, None] = '2b956706abb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key('challenge_id_key', 'challenge', ['id'])
    op.drop_constraint('challenge_name_key', 'challenge', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('challenge_name_key', 'challenge', ['name'])
    # ### end Alembic commands ###
