"""skins_table5

Revision ID: 9e999cfb1f23
Revises: 39dde0163d4d
Create Date: 2024-06-15 23:40:55.686330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e999cfb1f23'
down_revision: Union[str, None] = '39dde0163d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('skins', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'skins')
    # ### end Alembic commands ###
