"""qweeeeeeeeeeeeee

Revision ID: 9faed4dfdf55
Revises: b111b63f84ba
Create Date: 2024-06-22 23:04:23.273132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9faed4dfdf55'
down_revision: Union[str, None] = 'b111b63f84ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('target', sa.Integer(), nullable=False))
    op.add_column('challenge', sa.Column('reward', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge', 'reward')
    op.drop_column('challenge', 'target')
    # ### end Alembic commands ###
