"""skins_table6

Revision ID: b26469093a84
Revises: 9e999cfb1f23
Create Date: 2024-06-15 23:46:47.474596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26469093a84'
down_revision: Union[str, None] = '9e999cfb1f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_active_skin_fkey', 'user', type_='foreignkey')

    op.drop_column('skin', 'id')
    op.drop_column('user', 'active_skin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_skin', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_active_skin_fkey', 'user', 'skin', ['active_skin'], ['id'])
    op.add_column('skin', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('skin_id_seq'::regclass)"), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
