"""qwee

Revision ID: bbee05a1d051
Revises: 4e6bea8b0309
Create Date: 2024-06-22 22:57:55.805542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbee05a1d051'
down_revision: Union[str, None] = '4e6bea8b0309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('target', sa.Integer(), nullable=False))
    op.drop_constraint('challenge_user_id_fkey', 'challenge', type_='foreignkey')
    op.drop_column('challenge', 'description')
    op.drop_column('challenge', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('challenge', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('challenge_user_id_fkey', 'challenge', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('challenge', 'reward',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('challenge', 'target')
    # ### end Alembic commands ###
