"""skins_table

Revision ID: bc5f3fbb6f72
Revises: c08a8a0c718e
Create Date: 2024-06-15 23:09:20.660511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5f3fbb6f72'
down_revision: Union[str, None] = 'c08a8a0c718e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
