"""required_clicks_add

Revision ID: c08a8a0c718e
Revises: 44ee86c749e6
Create Date: 2024-06-15 22:05:30.303684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08a8a0c718e'
down_revision: Union[str, None] = '44ee86c749e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('required_clicks', sa.Integer(), nullable=False))
    op.drop_column('user', 'required_lvl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('required_lvl', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'required_clicks')
    # ### end Alembic commands ###
