"""skins_table8

Revision ID: eb71a283acd6
Revises: bc0fd220e66b
Create Date: 2024-06-15 23:55:18.759592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb71a283acd6'
down_revision: Union[str, None] = 'bc0fd220e66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'skin', ['name'])
    op.add_column('user', sa.Column('active_skin', sa.String(), nullable=False))
    op.create_foreign_key(None, 'user', 'skin', ['active_skin'], ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'active_skin')
    op.drop_constraint(None, 'skin', type_='unique')
    # ### end Alembic commands ###
