"""enter_time

Revision ID: f56526d4928b
Revises: 73893ed2b7a0
Create Date: 2024-06-19 15:30:48.492161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56526d4928b'
down_revision: Union[str, None] = '73893ed2b7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enter_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enter_time')
    # ### end Alembic commands ###
