"""schedule

Revision ID: f7650b9fdee5
Revises: e97a3d1f73eb
Create Date: 2024-06-22 23:41:27.373801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7650b9fdee5'
down_revision: Union[str, None] = 'e97a3d1f73eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge', sa.Column('active', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge', 'active')
    # ### end Alembic commands ###
